# Generated by Django 6.0.3 on 2026-03-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('genre', models.CharField(max_length=100, verbose_name='Genre')),
                ('description', models.CharField(max_length=1000)),
                ('duration', models.CharField(max_length=50, verbose_name='Duration')),
                ('poster', models.CharField(max_length=512, verbose_name='URL')),
            ],
        ),
    ]
