# Generated by Django 6.0.3 on 2026-03-13 08:19

from django.db import migrations

def create_data(apps, schema_editor):
    Movie = apps.get_model('tomovies', 'Movie')
    Movie(name="Hoppers", genre="Comedy",description="What if you could transfer your mind into an animal?", duration="140 minutes", poster='media/photo/nophoto.png').save()
    Movie(name="The Super Mario Bros Movie", genre="Adventure",description="It's Mario on the Big Screen!", duration="130 minutes", poster='media/photo/nophoto.png').save()
    Movie(name="The Godfather", genre="Crime Drama",description="When a Mafia boss hands over his empire to his son, things end up for the worse", duration="175 minutes", poster='media/photo/nophoto.png').save()

class Migration(migrations.Migration):

    dependencies = [
        ('tomovies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
