# Generated by Django 6.0.3 on 2026-04-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomovies', '0003_hall_session_price_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='hall_config',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hall',
            name='hall_price_standard',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='hall',
            name='hall_price_vip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
