# Generated by Django 6.0.3 on 2026-04-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomovies', '0005_alter_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
